apiVersion: apps/v1
kind: Deployment
metadata:
 name: db-deployment
 labels:
  name: myapp-db
  app: demo-myapp
spec: 
  selector:
    matchLabels:
      name: myapp-db
      app: demo-myapp
  replicas: 4
  template:
    metadata:
      name: db-pod
      labels:
        name: myapp-db
        app: demo-myapp
    spec:
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          env:
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_PASSWORD
            value: "postgres"      

  