
apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    name: myapp-redis
    app: demo-myapp
spec:
  containers:
    - name: redis
      image: redis 
      ports:
        - containerPort: 6379