apiVersion: v1
kind: Service
metadata: 
  name: redis
  labels:
    name: redis-service
    app: demo-myapp 
spec:
 ports:
   - port: 6379
     targetPort: 6379
 selector:
   name: myapp-redis
   app: demo-myapp