
apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-deployment
  labels:
    name: myapp-result
    app: demo-myapp
spec:
  selector:
    matchlabel:
      name: myapp-result
      app: demo-myapp
  replicas: 4
  template:
    metadata:
      name: result-app-pod
      labels:
        name: myapp-result
        app: demo-myapp
    spec:
      containers:
        - name: result-app
          image: kodekloud/examplevotingapp_result:v1
          ports:
            - containerPort: 80  
             
