apiVersion: v1
kind: Service
metadata: 
  name: voting-service
  labels:
    name: vote-service
    app: demo-myapp 
spec:
 type: NodePort 
 ports:
   
   - port: 80
     targetPort: 80
     nodePort: 30004
 selector:
   name: myapp-vote
   app: demo-myapp