apiVersion: v1
kind: Pod
metadata:
  name: voting-app-pod
  labels:
    name: myapp-vote
    app: demo-myapp
spec:
  containers:
    - name: vote-app
      image: kodekloud/examplevotingapp_vote:v1
      ports:
        - containerPort: 80