apiVersion: v1
kind: Pod
metadata:
  name: worker-pod
  labels:
    name: myapp-worker
    type: demo-myapp
spec:
  containers:
    - name: worker-app
      image: kodekloud/examplevotingapp_worker:v1
      