apiVersion: v1
kind: Pod
metadata:
  name: mypod-app
  labels:
    app: mypod
    type: front-end
spec:
  containers:
    - name: nginx-container
      image: nginx
      env:
        - name: NGINX_PASSWORD
          value: mypassword
    - name: busybox
      image: busybox-container  