apiVersion: v1
kind: ReplicationController
metadata: 
  name:  mmyapp-rc
  labels: 
    app: mypod-app
    type: front-end
spec:
  template:
    metadata:
      name: mypod-app
      labels:
        app: mypod
        type: front-end
    spec:
      containers:
      - name: nginx-container
        image: nginx
        env:
        - name: NGINX_PASSWORD
          value: mypassword
      - name: busybox
        image: busybox-container  
  replicas: 3      
    
    